#! /usr/bin/env bash

# Run various build tests (in source, install, etc) by essentially executing
# the commands shown in README.md files.
#
usage="usage: ./test c++-compiler [c++-compiler-option...]"

owd=`pwd`
trap "{ cd $owd; exit 1; }" ERR
set -o errtrace # Trap in functions.

if [ $# -eq 0 ]; then
  echo "$usage" 1>&2
  exit 1
fi

b=(b "config.cxx=$*")

#b+=(config.install.relocatable=true)

set -x


##
##
cd hello-simple/
"${b[@]}"
./hello
"${b[@]}" clean
cd "$owd"


##
##
cd hello-module/
"${b[@]}"
"${b[@]}" test
"${b[@]}" clean
cd "$owd"


##
##
cd hello-partition/
"${b[@]}"
"${b[@]}" test
"${b[@]}" clean
cd "$owd"


##
##
cd hello-library-module/

"${b[@]}" create: config/, cc
cd config/
b configure: ../libhello-format-module/@libhello-format-module/
b configure: ../libhello-module/@libhello-module/
b configure: ../hello-library-module/@hello-library-module/
b hello-library-module/
b test: hello-library-module/
cd ..
rm -rf config/

rm -rf /tmp/install
"${b[@]}"                                       config.install.root=/tmp/install install: libhello-format-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib config.install.root=/tmp/install install: libhello-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib hello-library-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib test: hello-library-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib clean: hello-library-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib clean: libhello-module/
"${b[@]}"                                       clean: libhello-format-module/
rm -rf /tmp/install

cd "$owd"


##
##
cd hello-utility-library-module/

"${b[@]}" create: config/, cc
cd config/
b configure: ../libhello-utility-module/@libhello-utility-module/
b configure: ../hello-utility-library-module/@hello-utility-library-module/
b hello-utility-library-module/
b test: hello-utility-library-module/
cd ..
rm -rf config/

rm -rf /tmp/install
"${b[@]}"                                       config.install.root=/tmp/install install: libhello-utility-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib                                           hello-utility-library-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib                                  test:    hello-utility-library-module/
"${b[@]}" config.cc.loptions=-L/tmp/install/lib                                  clean:   hello-utility-library-module/
"${b[@]}"                                                                        clean:   libhello-utility-module/
rm -rf config/

cd "$owd"
