cxx.std = latest
cxx.features.modules = true

using cxx

assert $cxx.features.modules "no modules support for $cxx.signature"

mxx{*}: extension = mxx
cxx{*}: extension = cxx

exe{hello}: {cxx mxx}{*}
